version: '3.2'

services:
  spring-eureka:
    image: com.springio.winter/eureka:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 8761:8761
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
  spring-demo:
    image: com.springio.winter/demo:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 8080:8080
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
  spring-config:
    image: com.springio.winter/config:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 9120:9120
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
  spring-gateway:
    image: com.springio.winter/gateway:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 9110:9110
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
  spring-admin:
    image: com.springio.winter/admin:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 9180:9180
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
  spring-zuul:
    image: com.springio.winter/zuul:0.0.1-SNAPSHOT
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "
        -server
        -Xms128M
        -Xmx128M
        -XX:SurvivorRatio=1
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:+UseCMSCompactAtFullCollection
        -XX:CMSFullGCsBeforeCompaction=0
        -XX:+CMSClassUnloadingEnabled
        -XX:LargePageSizeInBytes=128M
        -XX:+UseFastAccessorMethods
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:CMSInitiatingOccupancyFraction=80
        -XX:SoftRefLRUPolicyMSPerMB=0
        -XX:+PrintClassHistogram
        -XX:+PrintGCDetails
        -XX:+PrintGCTimeStamps
        -XX:+PrintHeapAtGC
        -Djava.awt.headless=true
        -XX:+HeapDumpOnOutOfMemoryError
        -Dspring.profiles.active=prod"
    ports:
    - 9111:9111
    networks:
    - winter
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    logging:
      options:
        max-size: 50m
networks:
  winter:
    external:
      name: winter_winter
